language: ruby
services:
  - mongodb
rvm:
  - 2.1.3
env:
  global:
    ERNEST_ADDRESS_ENDPOINT=http://ernest.dev
notifications:
  irc:
    channels:
    - irc.freenode.net#openaddresses
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
