worker1: bundle exec rake distiller:distil[1,5]
worker2: bundle exec rake distiller:distil[2,5]
worker3: bundle exec rake distiller:distil[3,5]
worker4: bundle exec rake distiller:distil[4,5]
worker5: bundle exec rake distiller:distil[5,5]
